1.Sayılardan oluşan bir boyutlu array oluşturun. Arrayi oluştururken sayıların veri tipini integer olarak belirtelim.

In [2]:
import numpy as np

In [3]:
dizi=np.array([20,50,68,45,60],dtype="int")

In [4]:
print(dizi)

[20 50 68 45 60]


Oluşturulan arrayin boyut, eleman sayısı bilgilerine bakalım.

In [9]:
boyut=dizi.ndim
boyut

1

In [10]:
elemanSayisi=dizi.size
elemanSayisi

5

2. Aşağıda verilen iki boyutlu ve üç boyutlu arrayi oluşturalım. Bu arraylerin boyut, eleman sayısı, satır, sütun bilgilerine ulaşalım.

İki boyutlu array:
[[1,2,6,7],
[4,3,9,5]]

Üç boyutlu array:
[[[7,5,14],[21,8,11]],
[[8,6,20],[14,3,9]]]

In [11]:
ikiBoyutluArray = np.array([[1,2,6,7], [4,3,9,5]])

In [12]:
ucBoyutluArray = np.array([[[7,5,14],[21,8,11]], [[8,6,20],[14,3,9]]])

In [13]:
#İki Boyutlu Arrayin Boyutu
ikiBoyutluArray.ndim

2

In [15]:
#Üç Boyutlu Arrayin Boyutu
ucBoyutluArray.ndim

3

In [16]:
#İki Boyutlu Arrayin Eleman Sayısı
ikiBoyutluArray.size

8

In [17]:
#Üç Boyutlu Arrayin Eleman Sayısı
ucBoyutluArray.size

12

In [18]:
#İki Boyutlu Arrayin Satır ve Sütun Bilgileri
np.shape(ikiBoyutluArray)

(2, 4)

In [19]:
#Üç Boyutlu Arrayin Satır ve Sütun Bilgileri
np.shape(ucBoyutluArray)

(2, 2, 3)

3. İstenilen elamanlara ulaşmak için arrayler üzerinde indexleme işlemi yapalım.

İki boyutlu arraydaki 2 elemanına ulaşalım.

In [20]:
ikiBoyutluArray[0,1]

2

İki boyutlu arraydaki 7 elemanına ulaşalım.

In [21]:
ikiBoyutluArray[0,3]

7

Üç boyutlu arraydaki 9 elemanına ulaşalım.

In [22]:
ucBoyutluArray[1,1,2]

9

Üç boyutlu arraydaki 5 elemanına ulaşalım.

In [23]:
ucBoyutluArray[0,0,1]

5

4. Arrayler üzerinde slicing işlemi uygulayalım.

İki boyutlu arraydaki 2,6 elemanlarına ulaşalım.

In [27]:
ikiBoyutluArray[0,1:3]

array([2, 6])

İki boyutlu arraydaki 3,9,5 elemanlarına ulaşalım.

In [25]:
ikiBoyutluArray[1,1:]

array([3, 9, 5])

Üç boyutlu arraydaki 21,8,11 elemanlarına ulaşalım.

In [28]:
ucBoyutluArray[0,1,:]

array([21,  8, 11])

Üç boyutlu arraydaki 6,20 elemanlarına ulaşalım.

In [29]:
ucBoyutluArray[1,0,1:]

array([ 6, 20])

5. 5 satır 3 sütunluk sıfırlardan ve birlerden oluşan iki tane iki boyutlu array oluşturalım. Bu arrayleri satır ve sütun bazında birleştirelim.

In [33]:
sifir=np.zeros((5,3), dtype = "int")
sifir

array([[0, 0, 0],
       [0, 0, 0],
       [0, 0, 0],
       [0, 0, 0],
       [0, 0, 0]])

In [34]:
bir=np.ones((5,3), dtype = "int")
bir

array([[1, 1, 1],
       [1, 1, 1],
       [1, 1, 1],
       [1, 1, 1],
       [1, 1, 1]])

In [35]:
np.concatenate([sifir,bir])

array([[0, 0, 0],
       [0, 0, 0],
       [0, 0, 0],
       [0, 0, 0],
       [0, 0, 0],
       [1, 1, 1],
       [1, 1, 1],
       [1, 1, 1],
       [1, 1, 1],
       [1, 1, 1]])